spring.application.name=Stud_result
#spring.datasource.url=jdbc:mysql://localhost:3306/student_db
#spring.datasource.username=root
#spring.datasource.password=Killerm4943a
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
##Hibernate Configuration
#
##'update' will automatically create/update tables based on your Entities
#
#spring.jpa.hibernate.ddl-auto=update
#
## Show SQL queries in the console (useful for debugging)
#
#spring.jpa.show-sql=true
#
#spring.jpa.properties.hibernate.format_sql=true
#spring.thymeleaf.check-template-location=false
#
##Dialect (Optional in newer Spring Boot versions, but good to have)
#
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.datasource.url=jdbc:mysql://localhost:3306/student_db
spring.datasource.username=root
spring.datasource.password=UqoCLNVuoSBxPczfZUshEaFquzvsRbTT
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.thymeleaf.check-template-location=false
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kathirlastmail@gmail.com
spring.mail.password=osti xnom pyvh axkj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.port=${PORT:8080}
